name: my-app

on:
  workflow_dispatch:

env:
  name: sulfeekar

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      title: gud boy

    steps:
      - name: env
        run: echo "my name is $name"

      - name: demo
        run: echo "my name is $name and i am a $title"
